environment: prod
project_name: globant
application: migration

resource_naming:
  prefix: ${project_name}-${application}-${environment}
  separator: "-"

bucket:
  versioning: true
  lifecycle_rules:
    - transition_to_intelligent_tiering_days: 90
    - transition_to_glacier_days: 180
    - expire_temp_files_days: 7

glue:
  workers: 5
  timeout_minutes: 120
  max_retries: 3

monitoring:
  alerts_email: prod-alerts@example.com
