name: Development Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install all dependencies
          pip install -r requirements.txt -r requirements-dev.txt
          # Install any missing test dependencies
          pip install pytest-mock boto3 moto pandas

      - name: Format code
        run: |
          black .
          isort .
          
      - name: Run linting
        run: |
          flake8 . --max-line-length=120 --extend-ignore=E302,W293,F401,E303 \
                   --exclude=.git,__pycache__,build,dist,.pytest_cache,.venv,cdk.out
          
      # - name: Run tests
      #   env:
      #     PYTHONPATH: ${GITHUB_WORKSPACE}
      #     AWS_DEFAULT_REGION: "us-east-1"
      #     AWS_ACCESS_KEY_ID: "testing"
      #     AWS_SECRET_ACCESS_KEY: "testing"
      #   run: |
      #     python -m pytest tests/ -v --import-mode=importlib
        
  deploy-dev:
    needs: validate
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install CDK
        run: npm install -g aws-cdk
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-duration-seconds: 1200
          mask-aws-account-id: true
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Deploy to Dev
        run: |
          aws sts get-caller-identity
          cdk deploy --require-approval never -c env=dev
        env:
          AWS_DEFAULT_REGION: us-east-1
